#
# Makefile for breath led devices
#

//obj-$(CONFIG_SN3193_SLED)		+= shineled_driver_find7op.o
obj-$(CONFIG_OPPO_MSM_FIND7)		+= shineled_driver_find7.o
obj-$(CONFIG_OPPO_MSM_14001)		+= shineled_driver_find7op.o
obj-$(CONFIG_OPPO_MSM_14091)		+= shineled_driver_find7.o
obj-$(CONFIG_OPPO_MSM_FIND7WX)		+= shineled_driver_find7.o